### ISSUE TITLE
vs project

### ISSUE THREAD

**Issue by kingvision** [elucideye/drishti#487]
Hi:
   can you provide a vs project?

thanks

**Comment by headupinclouds** [comment]
I need to provide some build documentation.  This project uses the [hunter package manager](https://github.com/ruslo/hunter), which is based on CMake.  CMake provides a variety of "generators" that can be used to create build projects for your preferred development environment directly from CMake source, so there are no plans to add explicit projects for each IDE (you can generate them).  

Here are some links from that project's documentation:

Hunter docs: https://docs.hunter.sh/en/latest/
Please read "Brief overview": https://docs.hunter.sh/en/latest/overview.html
And try "Quick start": https://docs.hunter.sh/en/latest/quick-start.html

For now, the Appveyor CI tests (see appveyor.yml) can serve as a sort of guide for VS builds until I get a chance to update documentation.  The Travis CI integration (.travis.yml) should cover the non Windows builds.

I make use of the [polly]( https://github.com/ruslo/polly) project for CMake toolchain abstractions and a small CMake front end called `polly.py`.  This isn't a hard requirement for builds (you can provide your own toolchains or let CMake use a platform default), but since it is a tested path, it may be easiest to start there.  (This makes the cross platform builds and tests much easier!)

I don't do any development with VS, but the Appveyor tests run regularly, so it should work.  Here is a rough outline of the build process extracted from the root level appveyor.yml.  Note that this will borrow the CI setup, and once you have installed a recent CMake and polly, you won't have to repeat that.  (It may be best to add the environment variables shown to your Windows configuration.)  This is a quick copy and paste w/ reformatting from that file (untested), but it should be close to functional.

```
set TOOLCHAIN "vs-14-2015-win64-sdk-8-1"
set CONFIG Release

set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%
pip install requests

# Install latest Polly toolchains and scripts (replace 'appveyor DownloadFile' w/ you your favorite tool)
appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
7z x master.zip
set POLLY_ROOT=%cd%\polly-master

# Install dependencies (CMake, Ninja)
python %POLLY_ROOT%\bin\install-ci-dependencies.py

# Tune locations
set PATH=%cd%\_ci\cmake\bin;%PATH%
set PATH=%cd%\_ci\ninja;%PATH%

# Add '--quiet' to avoid leaking the token to logs
git submodule update --init --recursive --quiet

# MSYS2 location
set MSYS_PATH=C:\msys64\usr\bin

# cd to drishti top level directory and run build
cd drishti
bin\build-appveyor.cmd "%CONFIG%" "%TOOLCHAIN%"
```

This should build a release with a library and various file based applications.  The real-time `facefilter` eye tracking demo is focused primarily on iOS and Android devices. The Windows Qt build currently has a small issue https://github.com/elucideye/drishti/issues/179 and is not functional.  I may add a small `sfml` based real-time demo that would run on Windows in the future.  If you add a `--open` option to the polly command in `build-appveyor.cmd` it should open the generated VS project automatically after the first build completes. 

```
python %POLLY_ROOT%\bin\polly.py ^
--open ^
--verbose ^
--archive drishti ^
--config "%1%" ^
--toolchain "%2%" ^
--test ^
--fwd HUNTER_USE_CACHE_SERVERS=ONLY ^
HUNTER_DISABLE_BUILDS=YES ^
DRISHTI_COPY_3RDPARTY_LICENSES=ON ^
DRISHTI_USE_TEXT_ARCHIVES=YES
```

You can check `polly.py --help` for a list of all available VS toolchains.  Note that if you use a new toolchain you will have to remove the `HUNTER_USE_CACHE_SERVERS` and `HUNTER_DISABLE_BUILDS` options to allow local package builds from source.  Hunter will build any required packages (i.e., OpenCV) along with any transitive dependencies, and a local cache will be populated, so subsequent build will be much faster.  I hope this helps!
