### ISSUE TITLE
why the newly released lib detects 65 eyelid keypoints?

### ISSUE THREAD

**Issue by saturosfz** [elucideye/drishti#498]
I use the newly released 2017.09.17 lib, and the EyeSegmenter detects 65 points of the eyelids. But the v0.8 lib detects 20 points. How can I control the number of points?

**Comment by headupinclouds** [comment]
For context, you are referring here to the eyelid contour points.  This contour is mostly to delineate the shape.  The estimation itself uses a 16 point contour, and the regression works in a lower dimensional space.  For the top level API, a smooth higher dimensional contour seems to be more useful (for drawing, etc).  We can update the API so that the user can retrieve the original 16 point model, or request some higher dimensional model provided via splines.

> How can I control the number of points?

This isn't possible with the current API.  If you look in       drishti/src/lib/drishti/drishti/EyeSegmenterImpl.cpp you will see the following call

```
model.refine();
```

You can provide a preferred point count like this:

```
model.refine(contourPointCount);
```

**Comment by headupinclouds** [comment]
I will create a separate issue to address this in the public API layer.
