### ISSUE TITLE
Feedback from a windows  build tried on master on 15-Oct-2017

### ISSUE THREAD

**Issue by kumaakh** [elucideye/drishti#585]
This was done before David added build instructions. May be it is addressed since.

-pulled master
-installed cmake 3.10 on win64
-started configure on c-make for VS2015:
issue 1) hunterGate complained about missing SHA1 hash I had no background on hunter till then, so switched repo to 0.8.4 tag

cmake/delete cache, cmake/configure
issue 2) msbuild.exe path not found, resolved by lauching cmake from Developer command Prompt
issues 3) the cmake script for VCTargetsPath installation complained toolset "v141" not installed => resolved by using -T "v140" during configure.

With this I could continue configure it took a lot of time specially in boost download, it also failed twice, but indistinctly I restarted configure and eventually it passed. I guess there is a undeclared dependency between cvmatio and boost. It appeared that if cvmatio built before boost it failed. It is a guess, I am not 100% sure hence not calling it an issue yet, certainly there is something that took 3 tries to generate entirely

-Now VS2015 solution built without fail aboslutely no issues.
-I could run all exe files, awesome looks like every thing is statitcally linked great

Finally while running drishti-face.exe I realized that it was not able to open *.jpg files, somehow libjpeg did not get linked though it was downloaded, built as i can see it insder c:\.hunter\
On windows OpenCV build is only using two dependencies: "PNG" and "ZLIB"

C:\.hunter\_Base\57d0748\e655aef\9d33353\Build\OpenCV\Dependencies>dir /b
PNG
ZLIB
It should at least have libJPEG, and also FFMPEG optionally

-Tweaked VideoSource.cpp to except .bmp files, and I could get my first face detection.

**Comment by headupinclouds** [comment]
Thanks for the notes.

> 1) hunterGate complained about missing SHA1 hash

I'm guessing that was due to a missing `drishti-upload` submodule, which contains a shared Hunter config (package versions + options) and a staged CMake build for binary server cache uploads.  If so, that would be fixed by:

```
git submodule update --init --recursive --quiet
```

> I guess there is a undeclared dependency between cvmatio and boost. It appeared that if cvmatio built before boost it failed

The cvmatio -> boost dependency looks okay at first glance.  The relevant lines from `cvmatio` are here:

https://github.com/hunter-packages/cvmatio/blob/b1d5e9f623094ce3c0a443d1cf7e8b5aebf6f971/CMakeLists.txt#L60

and here:
https://github.com/hunter-packages/cvmatio/blob/b1d5e9f623094ce3c0a443d1cf7e8b5aebf6f971/src/cmake/Config.cmake.in#L3

> With this I could continue configure it took a lot of time specially in boost download, it also failed twice

Failed == Timeout?

If you use `polly.py` to manage the builds it will dump indexed logs in `_logs/polly/${TOOLCHAIN}/log-?.txt`.  If you start with a fresh build `mv ${HOME}/.hunter ${HOME}/.hunter.bk` and `mv _builds _builds.bk` (windows equivalents) the logs could be helpful.

Actually, `cvmatio` is only needed to load `*.mat` files directly from Piotr's matlab code.  That is rarely used, and it should probably be disabled by default to streamline builds for the typical use case:

https://github.com/elucideye/drishti/blob/03f9b9b3538e6eba02ab13525c4b9d449ad77c5b/CMakeLists.txt#L384

> Finally while running drishti-face.exe I realized that it was not able to open *.jpg files, somehow libjpeg did not get linked though it was downloaded

The `cv::highgui` modules are controlled in the Hunter config here:

https://github.com/elucideye/drishti-upload/blob/27be92da07120107b7f6b5d5d280c1c4a5be95dd/config.cmake#L94

The JPEG libs are currently disabled for Windows here:

https://github.com/elucideye/drishti-upload/blob/27be92da07120107b7f6b5d5d280c1c4a5be95dd/cmake/Modules/drishti_set_opencv_cmake_args_windows.cmake#L22

If you change that locally and rebuild it should work.  Once the drishti hunter package is available, you would have the option of enabling this in your own project's config.

> It should at least have libJPEG, and also FFMPEG optionally

The default options are geared towards minimal size/time builds on mobile platforms.  You can change the various package dependencies in your fork or from a top level project.  The config for the top level project (or default package versions + options from hunter if not specified) is always used.  I think `ffmpeg` is not currently added to Hunter, so that dependency wouldn't be portable, and would have to be added manually for each platform.   There are `autoconf` schemes in Hunter, so `ffmpeg` could be added.

**Comment by headupinclouds** [comment]
Closing/migrating to gitter.

**Comment by headupinclouds** [comment]
> I could run all exe files, awesome looks like every thing is statitcally linked great

This is the case by default.  If you want to use the lib in a project that isn't using Hunter, there is a zero-dependency interface layer drishti/drishti that can be used as a shared library to contain the required symbols from the various static dependencies.  The console apps are currently using an internal OpenCV based SDK that isn't currently exported.  It might make sense to export that layer for direct use in Hunter.  There is some discussion about this here: https://github.com/elucideye/drishti/issues/574
