### ISSUE TITLE
Garbled output from cxxopts on windows

### ISSUE THREAD

**Issue by kumaakh** [elucideye/drishti#593]
Whenever I specify an option which is not really an option  I get a garbled message like following 

***** VIDEOINPUT LIBRARY - 0.1995 - TFW07 *****
Exception: Option ├óΓé¼╦£f├óΓé¼Γäó does not exist
Press any key to continue . . .

**Comment by headupinclouds** [comment]
Related https://github.com/jarro2783/cxxopts/pull/35 ?

**Comment by headupinclouds** [comment]
Fixed: https://github.com/jarro2783/cxxopts/pull/68 ?

It looks like this will be fixed by updating the hunter fork:

https://github.com/ruslo/hunter/blob/5dfe5ceb3b858a7f61e18ac61d46e2a4f5fb953f/cmake/projects/cxxopts/hunter.cmake#L18

https://docs.hunter.sh/en/latest/contributing.html
https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by kumaakh** [comment]
OK I reviewed the above, its'not clear to me who uploads the new tar.gz to 
https://github.com/hunter-packages/cxxopts/releases ? 
cxxopts has release 1.4.3 is available here
https://github.com/jarro2783/cxxopts/archive/v1.4.3.tar.gz
Can I not just use the above address  at 
https://github.com/ruslo/hunter/blob/5dfe5ceb3b858a7f61e18ac61d46e2a4f5fb953f/cmake/projects/cxxopts/hunter.cmake#L18  
along with the correct sha1 and version number ?
