### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by binaryroot** [elucideye/drishti#633]
Hello,
Could you please help me with compiling app for android platform. I have the following error during perform build-android.sh.

` sudo /Users/nazariii/Development/gl/ogles_gpgpu-hunter-2/bin/build-android.sh
Python version: 3.6
Build dir: /_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release
Execute command: [
  `which`
  `cmake`
]

[/]> "which" "cmake"

/usr/local/bin/cmake
Execute command: [
  `cmake`
  `--version`
]

[/]> "cmake" "--version"

cmake version 3.9.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Execute command: [
  `cmake`
  `-H.`
  `-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release`
  `-DCMAKE_BUILD_TYPE=Release`
  `-GUnix Makefiles`
  `-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake`
  `-DCMAKE_VERBOSE_MAKEFILE=ON`
  `-DPOLLY_STATUS_DEBUG=ON`
  `-DHUNTER_STATUS_DEBUG=ON`
  `-DOGLES_GPGPU_BUILD_TESTS=ON`
  `-DOGLES_GPGPU_OPENGL_ES3=OFF`
  `-DHUNTER_CONFIGURATION_TYPES=Release`
  `-DGAUZE_ANDROID_USE_EMULATOR=YES`
]

[/]> "cmake" "-H." "-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release" "-DCMAKE_BUILD_TYPE=Release" "-GUnix Makefiles" "-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DPOLLY_STATUS_DEBUG=ON" "-DHUNTER_STATUS_DEBUG=ON" "-DOGLES_GPGPU_BUILD_TESTS=ON" "-DOGLES_GPGPU_OPENGL_ES3=OFF" "-DHUNTER_CONFIGURATION_TYPES=Release" "-DGAUZE_ANDROID_USE_EMULATOR=YES"

CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Command exit with status "1": [/]> "cmake" "-H." "-B/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release" "-DCMAKE_BUILD_TYPE=Release" "-GUnix Makefiles" "-DCMAKE_TOOLCHAIN_FILE=/Users/nazariii/Development/gl/polly-master/android-ndk-r10e-api-19-armeabi-v7a-neon.cmake" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DPOLLY_STATUS_DEBUG=ON" "-DHUNTER_STATUS_DEBUG=ON" "-DOGLES_GPGPU_BUILD_TESTS=ON" "-DOGLES_GPGPU_OPENGL_ES3=OFF" "-DHUNTER_CONFIGURATION_TYPES=Release" "-DGAUZE_ANDROID_USE_EMULATOR=YES"

Log: /_logs/polly/android-ndk-r10e-api-19-armeabi-v7a-neon/log.txt
*** FAILED ***
`

**Comment by headupinclouds** [comment]
It looks like you are trying to build `ogles_gpgpu`.  Is this the case?  If you are, then please move the questions to that repository.

If you are want to build `drishti`, then you don't have to build `ogles_gpgpu` on your own, since the dependency will be managed by hunter.

If you were trying to build `drishti` and were having problems, then ...

The `./bin/*.sh` files are legacy build scripts that I have used for application specific builds at various points.  The build scripts in drishti require that a top level `DRISHTISDK` environment variable is set.  I will remove them soon, as I think they cause some unnecessary complexity and confusion.  The README page provides more general direct build instructions using `polly.py` that should work fine:

```
polly.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --fwd HUNTER_CONFIGURATION_TYPES=${CONFIG} --install --verbose
```
Additional cmake options can be added by providing `KEY=VALUE` pairs in the `--fwd` list.

**Comment by binaryroot** [comment]
Yes i am trying to build ogles_gpgpu.
Thank you, I will move the issue to that branch.
