### ISSUE TITLE
Build samples for Android.

### ISSUE THREAD

**Issue by gera-gas** [elucideye/drishti#639]
Hi I building drishti with following parameters for Adnroid under Linux:

export PATH=~/develop/drishti/polly/bin:~/develop/tools/cmake/bin:$PATH
export ANDROID_NDK_r10e=~/develop/tools/android-ndk/android-ndk-r10e
bin/drishti_build.sh android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections Release --strip

File content of drishti_build.sh:
ARGS=(
    --toolchain "${TOOLCHAIN}"
    --config "${CONFIG}"
    --verbose
    --ios-multiarch --ios-combined
    --fwd ANDROID=TRUE
    DRISHTI_BUILD_SHARED_SDK=YES
    DRISHTI_BUILD_TESTS=NO
    DRISHTI_BUILD_EXAMPLES=YES
    DRISHTI_COPY_3RDPARTY_LICENSES=ON
    GAUZE_ANDROID_USE_EMULATOR=NO
    HUNTER_CONFIGURATION_TYPES="${CONFIG}"
    HUNTER_SUPPRESS_LIST_OF_FILES=ON
    --archive drishti
    --jobs 2
    --test      
    "${INSTALL}"
)

polly.py ${ARGS[@]} --reconfig

The first what I want - build examples for android (*.apk).
In build result I have a several *.elf files for ARM architecture (_install/drishti_eye, etc), and I don't find *.apk files.

I think, may be I should switch-on tests by DRISHTI_BUILD_TESTS=YES, but test failed in my device.

chunk of tests log:
1: [----------] 2 tests from HCITest
1: [ RUN      ] HCITest.RunTestCPUAsync
1: /home/gera/develop/drishti/drishti/src/lib/drishti/hci/ut/test-drishti-hci.cpp:199: Failure
1: Expected: (monitor.getFaces().size()) > (0), actual: 0 vs 0
1: [  FAILED  ] HCITest.RunTestCPUAsync (1780 ms)
1: [ RUN      ] HCITest.RunTestGPUAsync
1: /home/gera/develop/drishti/drishti/src/lib/drishti/hci/ut/test-drishti-hci.cpp:199: Failure
1: Expected: (monitor.getFaces().size()) > (0), actual: 0 vs 0
1: [  FAILED  ] HCITest.RunTestGPUAsync (1380 ms)
1: [----------] 2 tests from HCITest (3160 ms total)
1:
1: [----------] 2 tests from EyeSegmenter
1: [ RUN      ] EyeSegmenter.StringConstructor
1: [       OK ] EyeSegmenter.StringConstructor (199 ms)
1: [ RUN      ] EyeSegmenter.StreamConstructor
1: [       OK ] EyeSegmenter.StreamConstructor (195 ms)
1: [----------] 2 tests from EyeSegmenter (394 ms total)
1:
1: [----------] 6 tests from EyeSegmenterTest
1: [ RUN      ] EyeSegmenterTest.EyeSerialization
1: [       OK ] EyeSegmenterTest.EyeSerialization (950 ms)
1: [ RUN      ] EyeSegmenterTest.ImageEmpty
1: [       OK ] EyeSegmenterTest.ImageEmpty (944 ms)
1: [ RUN      ] EyeSegmenterTest.ImageTooSmall
1: [       OK ] EyeSegmenterTest.ImageTooSmall (925 ms)
1: [ RUN      ] EyeSegmenterTest.ImageValid
1: [       OK ] EyeSegmenterTest.ImageValid (4007 ms)
1: [ RUN      ] EyeSegmenterTest.ImageIsBlack
1: [       OK ] EyeSegmenterTest.ImageIsBlack (937 ms)
1: [ RUN      ] EyeSegmenterTest.ImageIsWhite
1: [       OK ] EyeSegmenterTest.ImageIsWhite (936 ms)
1: [----------] 6 tests from EyeSegmenterTest (8700 ms total)
1:
1: [----------] 1 test from FaceTest
1: [ RUN      ] FaceTest.RunSimpleTest
1: [       OK ] FaceTest.RunSimpleTest (2818 ms)
1: [----------] 1 test from FaceTest (2818 ms total)
1:
1: [----------] Global test environment tear-down
1: [==========] 29 tests from 12 test cases ran. (30617 ms total)
1: [  PASSED  ] 27 tests.
1: [  FAILED  ] 2 tests, listed below:
1: [  FAILED  ] HCITest.RunTestCPUAsync
1: [  FAILED  ] HCITest.RunTestGPUAsync
1:
1:  2 FAILED TESTS
1: 1
1: *** END ***
1: CMake Error at _3rdParty/gauze_test/DrishtiTest.cmake:228 (message):
1:   Command exits with error code: 1

How I can get a samples with drishti demo (*.apk) for run it in my android device?

**Comment by headupinclouds** [comment]
If you add `DRISHTI_BUILD_QT=ON` to the CMake option list (in polly it is `polly.py ... --fwd DRISHTI_BUILD_QT=ON`) it will enable the Qt package and the facefilter application.  Note: The Qt package can take a long time to build.  That will also enable the real-time facefilter sample application.  Before you run, you will have to add an entry to the config file for the basic intrinsic camera parameters using a name corresponding to the ID (according to Qt) of your device/camera.  

See:

https://github.com/elucideye/drishti/blob/a7f42af6bf1c6e367ff400b79c27c96967d72886/src/app/qt/facefilter/facefilter.json#L62-L78

```
    "front": {
        "description": "Front-facing camera",

        "sensor": {
            "intrinsic": {
                "size": {
                    "width": 2560,
                    "height": 1440
                },
                "principal": {
                    "x": 1280.0,
                    "y": 720.0
                },
                "focal_length_x": 1000.0
            }
        }
    },
```

I'm not sure why your tests are failing.  The same tests should run on the emulator during CI builds.  What device are you using?

**Comment by gera-gas** [comment]
Thanks for answer! Today I try to do it. I using Alcatel 5010D (PIXI 4), before test I enable debug by USB in device.

**Comment by gera-gas** [comment]
Hi, I add `DDRISHTI_BUILD_QT=ON`, but now I have a following bug:
```
Building Android package using ant.
Using ant: /home/gera/develop/tools/apache-ant/bin/ant
Buildfile: /home/gera/develop/drishti/drishti/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections-Debug/src/app/qt/facefilter/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.2.5
 [checkenv] Installed at /home/gera/.hunter/_Base/32f280c/3ce59a5/a5d4092/Install/android-sdk

-setup:
     [echo] Project Name: QtApp
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for QtApp...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
     [echo] ----------
     [echo] Resolving Dependencies for QtApp...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Found modified input file
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] Found 2 AIDL files.
     [aidl] Compiling 2 AIDL files.

BUILD FAILED
/home/gera/.hunter/_Base/32f280c/3ce59a5/a5d4092/Install/android-sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/gera/.hunter/_Base/32f280c/3ce59a5/a5d4092/Install/android-sdk/tools/ant/build.xml:655: Execute failed: java.io.IOException: Cannot run program "/home/gera/.hunter/_Base/32f280c/3ce59a5/a5d4092/Install/android-sdk/build-tools/22.0.1/aidl" (in directory "/home/gera/develop/drishti/drishti/_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-hid-sections-Debug/src/app/qt/facefilter"): error=2, file is missing.
```
But I after this bug I saw directory and aidl exist.

**Comment by headupinclouds** [comment]
Sorry for the delay.  It's hard to know what's going on based on that log.  This is using ant based command line apk packaging to facilitate deploying on the device.  The CMake module is here:

https://github.com/hunter-packages/android-apk

There are some small apk packaging sample projects which use this that might be worth testing on your setup + device to help debug the issue you are facing (I suspect you are probably quite close to being able to run):

https://github.com/forexample/android-cmake

That said, since ant has been removed from recent Android Studio releases, and CMake is now a first class citizen, this stuff will be dropped for facefilter in the near future in favor of an official Gradle + CMake build.  The latest Android Studio 3.2 Canary 4 now supports use of standard/external/non-bundled CMake > 3.7, which makes this project buildable in Android Studio through CMake (https://github.com/forexample/android-studio-with-hunter).  

Qt itself will also be dropped in the near future in favor of lightweight native iOS and Android facefilter projects, which should be much faster for this build-from-source project.  The facefilter demo is the one part that isn't covered by CI builds, due to Qt build times, so moving to native projects should also make that possible.

**Comment by tedcaldwell** [comment]
Hi, just wondering if there is anything to report on the Qt-free facefilter app? We are evaluating Drishti for a project, but finding it slow going as we are new to CMake, etc.
Any general tips on how to speed up builds in general, or whether we'd be foolhardy to try to de-Qt-ify the app ourselves?
Thanks...

**Comment by headupinclouds** [comment]
Hi Ted.  

> just wondering if there is anything to report on the Qt-free facefilter app

Not yet.  (I'm assuming you are targeting Android based on this issue's title.)  I've been busy with some other work lately.  I don't think the external/standard CMake support in Android Studio has made it out of the Canary channel yet.  That is kind of a prerequisite for using Hunter, so I wouldn't add the native stuff until that functionality is stable.

> Any general tips on how to speed up builds in general, 

This project uses Hunter, so all dependencies will be cached, which means your build will radically reduce after your first end-to-end build, as you'll only be building your in-repo code at that point.  You can also configure a network/server cache to share between users, but I wouldn't recommend that until you are more familiar with Hunter.  If you build with polly you can also experiment with `--jobs N` to try to speed things up.

There can be a learning curve for CMake, but IMHO the effort is well worth it.  Ruslo maintains a nice modern CMake overview that is worth a read here: https://cgold.readthedocs.io/en/latest/

I'm not sure what problems you are facing, but the `.travis.yml` and `appveyor.yml` scripts can serve as a functioning build reference.  If you have more specific questions I can try to help.  There is also a gitter channel for Hunter specific questions where people are typically very helpful.

> or whether we'd be foolhardy to try to de-Qt-ify the app ourselves?

The main challenge for mobile (iOS + Android) is handling the input camera -> GPU feed efficiently.  This assumes real-time performance and/or per frame rendering/VR/AR is critical for your application.  For iOS platforms, this is supported by the iOS texture cache (as implemented in GPUImage(2)).  In recent Android releases, this is handled in the Java layer through Camera 2 + SurfaceTextures.  If your team is familiar with this stuff, it might not be a significant effort, otherwise it could take a few weeks.

Sorry I don't have a more concrete timeline for the Qt replacement.  I just need to find enough weekend/evening time to make it happen, which can be harder in Summer :)  I'll be sure to post updates here.

**Comment by tedcaldwell** [comment]
Hi David - I'm actually working in iOS, but happened across this thread because I was trying to figure out how to build the Qt app. 

We'll stick with the Qt code for now - BTW, I ran into a known Qt issue when building for ios 11.3, which is documented here, in case that helps someone: https://wiki.qt.io/Qt_5.9.5_Known_Issues

Anyway, thanks for your help!

**Comment by swkonz** [comment]
Hi - Any advice on how to go about getting the intrinsic camera parameters and device ID for QT to add to the json file? I'm new to QT and I've been having trouble finding clear directions. Thanks!

**Comment by headupinclouds** [comment]
see #701, src/examples/facefilter/android-studio should build as a standard android project (requires 3.2 beta for external cmake support)
