### ISSUE TITLE
Android integration.

### ISSUE THREAD

**Issue by ViktorSkabiak** [elucideye/drishti#665]
Hi everyone. Could you please help me with this project integration in my Android application?
Please provide some useful link or completed examples which demonstrates how to use real time eye tracking for Android devices. Thanks))

**Comment by headupinclouds** [comment]
Hi Viktor. 

In general there are two ways to integrate:

1) Use [Hunter](https://docs.hunter.sh/en/latest/) to manage your dependencies.  

You can look at the `src/app/{face, eye}` samples in this project:

https://github.com/elucideye/drishti_hunter_test

which is currently set up to use drishti through Hunter with the `GIT_SUBMODULE` feature.

To do this cleanly in Android Studio, you can use an approach like this: 

https://github.com/forexample/android-studio-with-hunter

which currently requires that you use the Canary Channel, since early versions use a non-standard CMake that doesn't play well with Hunter.  There are a few API update in progress here, so it is best to use the latest drishti release through Hunter with the `GIT_SUBMODULE` feature as described [here](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html#use-version-from-git-submodule).

2) You can build a shared library (or iOS dynamic framework) so you only have a single library to drop into your project.  You can build the lib following the README instructions or find a matching toolchain from the tagged [releases](https://github.com/elucideye/drishti/releases) and the install tree will contain the headers and lib that you need, in addition to CMake relocatable package info sufficient for using `find_package(drishti CONFIG REQUIRED) target_link_libraries(app PUBLIC drishti::drishti)` through CMake in a project without Hunter.  You can also just link the libraries using whatever build system you are working with.  

I will try to get some iOS and Android Studio samples added for the Hunter case (1) above sometime in June.  This will most likely take the form of an update to https://github.com/elucideye/drishti_hunter_test.

**Comment by headupinclouds** [comment]
see #701 , readme updates will follow shortly, but `src/examples/facefilter/android-studio` should build as a standard project now (requires >= 3.2 beta for external cmake support)

**Comment by ViktorSkabiak** [comment]
@headupinclouds Great!)) Thanks you for your help
