### ISSUE TITLE
Android compilation fails

### ISSUE THREAD

**Issue by matejsteinbacher** [elucideye/drishti#695]
Hello there:

I am trying to compile the drishti library for Android (commit 2a8759a8fc4f69d34cef9a174d4d3b9188aa1240) with the following toolchain and params:

export TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon && export CONFIG=Debug && source bin/hunter_env.sh

./../polly/bin/polly.py --toolchain "${TOOLCHAIN}" --config "${CONFIG}" --verbose --fwd DRISHTI_BUILD_QT=ON ANDROID=FALSE DRISHTI_BUILD_SHARED_SDK=YES DRISHTI_BUILD_TESTS=NO  DRISHTI_BUILD_EXAMPLES=YES DRISHTI_COPY_3RDPARTY_LICENSES=ON GAUZE_ANDROID_USE_EMULATOR=NO HUNTER_CONFIGURATION_TYPES="${CONFIG}" HUNTER_SUPPRESS_LIST_OF_FILES=ON BUILD_SHARED=ON --archive drishti --jobs 6 --test --install --reconfig

The compilation fails while building the dlib with the error:

/.hunter/_Base/34d985c/09c84d9/840b61a/Build/dlib/Source/dlib/bigint/../serialize.h:1635:25: error: 'to_string' is not a member of 'std' std::to_string(objects_read+1) + "th object from the file " + filename +

Changing a toolchain for something else wouldn't help. 

In the past I could compile the library for the Android and could use it well in Windows/Linux/Android. I just needed to comment-out the line caused by a Qt-related error (drishti/src/app/qt/facefilter/main.cpp: (comment-out line 54)).

Does any have the same issue and are there any toolchains/configurations preferred for the Android? I am using GCC 7.3.0 or clang 6.0.0 and Ubuntu 18.04 LTS.

The whole log: https://drive.google.com/file/d/1hxGj9bAPcru4KyXA9nBu5ZHlnfwNlw2v/view?usp=sharing

Thanks a lot
Matej

**Comment by headupinclouds** [comment]
Hi.  This is related to a `C++11` language requirement in `drishti` and dependencies.  The `gcc` + `libstdc++` toolchain used in `android-ndk-r10e-api-19-armeabi-v7a-neon` only has partial C++11 support.  There are various patches (`std::to_string()`, etc) in both this library and `acf` to accommodate such older toolchains, but the issue you mention is in the `dlib` dependency (it requires C++11).  We had been maintaining support for that older partial C++11 toolchain as a kind of special case until the NDK 17 release, where clang is now the official compiler (gcc will be removed soon).

1) Use a fully C++11 compliant toolchain such as [android-ndk-r17-api-19-armeabi-v7a-neon-clang-libcxx](https://github.com/elucideye/drishti/blob/2a8759a8fc4f69d34cef9a174d4d3b9188aa1240/.travis.yml#L116)

:point_up: Does this work for you?

2) Use an older version of dlib in your local Hunter config (I believe you will also need to use an older  nlohman_json package)

```
if(ANDROID)
  # https://travis-ci.org/ingenue/hunter/jobs/287844545
  # Will be fixed in Android NDK 17
  set(dlib_version 19.2-p1)
else()
  set(dlib_version 19.6-p2)
endif()

set(dlib_cmake_args
  DLIB_HEADER_ONLY=OFF  #all previous builds were header on, so that is the default
  DLIB_ENABLE_ASSERTS=OFF #must be set on/off or debug/release build will differ and config will not match one
  DLIB_NO_GUI_SUPPORT=ON
  DLIB_ISO_CPP_ONLY=OFF # needed for directory navigation code (loading training data)
  DLIB_JPEG_SUPPORT=OFF  # https://github.com/hunter-packages/dlib/blob/eb79843227d0be45e1efa68ef9cc6cc187338c8e/dlib/CMakeLists.txt#L422-L432
  DLIB_LINK_WITH_SQLITE3=OFF
  DLIB_USE_BLAS=OFF
  DLIB_USE_LAPACK=OFF
  DLIB_USE_CUDA=OFF
  DLIB_PNG_SUPPORT=ON
  DLIB_GIF_SUPPORT=OFF
  DLIB_USE_MKL_FFT=OFF
  HUNTER_INSTALL_LICENSE_FILES=dlib/LICENSE.txt
)

hunter_config(dlib VERSION ${dlib_version} CMAKE_ARGS ${dlib_cmake_args})
```

**Comment by matejsteinbacher** [comment]
Many thanks for the reply.

"android-ndk-r17-api-19-armeabi-v7a-neon-clang-libcxx" was declined by polly as a wrong toolchain by producing the following error message:

polly.py: error: argument --toolchain: invalid choice: 'android-ndk-r17-api-19-armeabi-v7a-neon-clang-libcxx' (choose from 'default', ...).

I've got the message and will try with other options.

Thanks
Matej

**Comment by headupinclouds** [comment]
see https://github.com/ruslo/polly/blob/master/android-ndk-r17-api-19-armeabi-v7a-neon-clang-libcxx.cmake

Try `cd polly && git pull` :smile:

**Comment by matejsteinbacher** [comment]
Thanks for the link - I cloned polly from the elucideye's side.

But the Qt issue is still present. Does Qt have to be separately built and then linked to the drishti?

Matej

**Comment by headupinclouds** [comment]
> Does Qt have to be separately built and then linked to the drishti?

Not by design, it should all build from source.  In practice, it is a challenge keeping the Qt package up to date with the iOS and Android SDK's.  The plan is to move to native code.  I've been busy and haven't found time to make it happen.   For now, if you want to use facefilter + Android you may want to use your old tested toolchain and just craft a local `cmake/Hunter/config.cmake` file to use the non-C++11 package workarounds (this should basically just be the `cmake/Hunter/config.cmake` from the commit you were using last + the most recent `acf` `hunter_config()` from the latest configs).  You will need to specify `LOCAL` in your HunterGate call.  If you need help let me know and I will try to get something working.

The Qt errors in your log seem to be due to a missing system include path somewhere.  These basic headers aren't found:

```
> /home/matej/.hunter/_Base/34d985c/1908103/840b61a/QtBuild/14/qtbase/config.tests/common/alloca/alloca.cpp:47:21: fatal error: malloc.h: No such file or directory
>  # include <malloc.h>
>                      ^
> compilation terminated.
```
```
> /home/matej/.hunter/_Base/34d985c/1908103/840b61a/QtBuild/14/qtbase/config.tests/common/alloca/alloca.cpp:49:21: fatal error: stdlib.h: No such file or directory
>  # include <stdlib.h>
>                      ^
> compilation terminated.
```

That probably requires a Qt package update.  Ruslo put the Qt package together, and since it is non-crake based, it probably has more pitfalls.  It may take some digging to sort through that.

I *think* a gcc + libcxx combination might work, but need to test it.   I'm guessing ndk + gcc will provide the correct include paths and the libcxx part will provide C++11 compatibility.  Something like: `android-ndk-r17-api-19-armeabi-v7a-neon-gcc-libcxx` (needs to be created).   Maybe one of these options will be a viable workaround for now.

**Comment by matejsteinbacher** [comment]
Many thanks again

Do I read the lines correctly that Qt isn't quite on your priority list (and might even get dropped)?

I'll try the proposed solution and then be back with results.

Matej

**Comment by headupinclouds** [comment]
> Do I read the lines correctly that Qt isn't quite on your priority list (and might even get dropped)?

That's correct.  The idea is that native apps will be easier to maintain, will be more flexible (Android Camera 2, native face detection when applicable, etc), and easier to support in the CI configuration.  I think it will also be more accommodating to a larger group of users.   Do you want/need Qt in particular?  I guess I'm assuming nobody else wants to maintain the Qt package.  (Ruslo did all of the Qt package work, and I think he's the only one updating it.)

**Comment by headupinclouds** [comment]
> Temporarily, I ended-up with the following setup:

Thanks for posting.  I'll take a look later.  Does it seem like a general solution?

**Comment by headupinclouds** [comment]
>  I have a version that uses Android.camera2 framework but mixing it with the JNI, it causes a run-time error. Detector would crash at the make shared pointer call. 

I'm not sure I follow this 100%, and without more info it is hard to say exactly, but I would guess the issue is that there is no OpenGL context created at the time you are trying to create the OpenGL accelerated ACF detector.

> Istreams were passed as arguments and not strings to model files. Qt example was then considered as an escape hedge because of those errors and isn't preferred at all.

I don't know if this is what you are referring to, but Qt uses its own resource manager that is stream based, so the `facefilter` example has to create a QtFaceDetectorFactory derived class to work based on that input.  Native iOS and Android obviously don't have that restriction.

**Comment by matejsteinbacher** [comment]
The whole last comment referred to the native Android framework. Since it was mentioned that native Android is your direction to go (with Android.camera2) then it'd make sense for me to continue with the native framework as well. 

I'm closing the issue. Any further comments wouldn't fall under the topic.

Thanks again
Matej

**Comment by matejsteinbacher** [comment]
Hello - I am reopening the issue.

The version that I managed to build doesn't run correctly. It runs but doesn't show much. This can also be due to the phone's camera (it's Samsung). I'd highly appreciate, if it's possible to get something working to compile the most recent Drishti with Qt support.

Many thanks
Matej
