### ISSUE TITLE
Problems with porting to the Android

### ISSUE THREAD

**Issue by matejsteinbacher** [elucideye/drishti#696]
Hello there:

I am trying to get drishti running on an Android but haven't managed yet. On Windows/Linux it all worked like a charm.

1. Demo images on the page would be close to what I'd like, so I'm wondering if there exists a known version that created them?

2. Version with Qt somehow works (an older commit w/o C++11 support and only in the Release mode), but errors appeared also there. For instance, a call to a function "getChannels()". More importantly, running the application wouldn't show any markings and also exiting it had to be done by force.

3. Using drishti outside of the repository as a library, seem not to include all modules. As a workaround, I manually included paths to other sources, for instance to folders core, face. It looks awkward, though working. Would be any more convenient way suggested?

4. On Android I try to integrate example "face.cpp" into the Android Studio-based application. The whole "drishti" part is modeled inside the JNI. My current version compiles but produces a runtime error at the creation of the 
	"auto detector = drishti::core::make_unique<drishti::face::FaceDetector>(*factory);"

I checked all istreams and are valid and their sizes match sizes of input models. The error suggests that something is not set properly (SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0))). This is how I created the factory and the line passes well.
auto factory = drishti::core::make_unique<drishti::face::FaceDetectorFactoryStream>(
        apStreams->m_isFaceDetector,
        apStreams->m_isFaceRegressor,
        apStreams->m_isEyeRegressor,
        apStreams->m_isFaceModel
    );

Any hints?

Thanks
Matej

**Comment by headupinclouds** [comment]
Hi Matej.  We are aiming to replace the Qt facefilter example with native iOS/Android code this weekend.  I think it will make sense for you to wait until that has been added.

> 1) .. if there exists a known version that created them?

The readme page images were created with `drishti-eye` console application, which expects eye images (not face images) with a 4:3 aspect ratio that look similar to the examples (same relative scale, etc).

> 2) Version with Qt somehow works 

We will be replacing this with native app for iOS/Android which will make it more CI friendly and should provide an easier "quick start"

> 3) Using drishti outside of the repository as a library, seem not to include all modules.

Currently the installed public API (supported via `find_package(drishti CONFIG REQUIRED)` and hunter) is in src/lib/drishti/drishti.  This doesn't expose external types (`cv::Mat`, etc) and should be friendlier for folks wanting to build a single shared (dependency free) library to drop into projects without using hunter or cmake.  There are working examples using this SDK in the following application directory https://github.com/elucideye/drishti/tree/master/src/app/sdk

> 4) current version compiles but produces a runtime error at the creation of the

My hunch is that it isn't a stream error.  If you are using ACF w/ OpenGL acceleration then you need to have an active OpenGL context at the time you create everything. 

I'll aim to get the sample code updated this weekend.  I've been a little busy with some other projects.

**Comment by matejsteinbacher** [comment]
It's running now. Still not fully satisfied with it and would be eager to see your solution.

Thanks
Matej

**Comment by headupinclouds** [comment]
I hope to merge a PR with the native Android + iOS apps using the installed package `hunter_config(drishti GIT_SELF ...)` sometime early next week.  I'll post an update here.

**Comment by xsacha** [comment]
I have successfully integrated a modern Qt version supporting Android/iOS/everything else.
It did take a lot of work but the final product makes it look easy.
Biggest hint I could give is don't bother with CPU version because Android orientation is all messed up in that version. Just go straight for GL texture version.

To get autofocus on the camera you need to add this in QML:
```focus.focusMode: focus.isFocusModeSupported(CameraFocus.FocusContinuous) ? 
CameraFocus.FocusContinuous : CameraFocus.FocusAuto
       focus.focusPointMode: focus.isFocusPointModeSupported( CameraFocus.FocusPointCenter)   ?  CameraFocus.FocusPointCenter : CameraFocus.FocusPointAuto
```

or this in the C++:
```QCameraFocus* focusObj = m_mediaObject->focus();
            for (auto p : {QCameraFocus::FocusPointFaceDetection, QCameraFocus::FocusPointCenter, QCameraFocus::FocusPointAuto})
            {
                if (focusObj->isFocusPointModeSupported(p))
                {
                        focusObj->setFocusPointMode(p);
                        break;
                }
            }
            for (auto f : {QCameraFocus::FocusMode::ContinuousFocus, QCameraFocus::FocusMode::AutoFocus})
            {
                if (focusObj->isFocusModeSupported(f))
                {
                        focusObj->setFocusMode(f);
                        break;
                }
            }```


Good luck.

**Comment by headupinclouds** [comment]
@matejsteinbacher See #701 .  Sorry for the wait.  I'll try to get documentation in place soon, but after the merge, it should essentially be a standard Android Studio build from here:

https://github.com/elucideye/drishti/tree/pr.native.apps/src/examples/facefilter/android-studio

This requires 3.2 beta for external (standard) CMake support.

**Comment by matejsteinbacher** [comment]
I've briefly checked and it looks a nice job - congrats

Thanks a lot
Matej

**Comment by matejsteinbacher** [comment]
Hi again:

Just tried to build it. Drishti compiled from the source w/o a problem but building inside the Android Studio (AS) failed. The error:

hunter ** FATAL ERROR **] Git directory is dirty: '/home/matej/temp/t/drishti/master.zip'
[hunter ** FATAL ERROR **] Please commit or stash changes.
[hunter ** FATAL ERROR **] [Directory:/home/matej/temp/t/drishti/src/examples/drishti-upload] 

In addition, it might be worth creating the file "local.properties", which, if not existent, is automatically created by the AS. The file should be modified to add the path to the CMake. Default version of the CMake that AS uses is inferior to the Drishti's requirement. In addition, since you already download CMake, you might additionally download "ninja" and put it inside the CMake's bin folder, since it's used by the AS.

local.properties
ndk.dir=/XXX/Android/Sdk/ndk-bundle
sdk.dir=/XXX/Android/Sdk
cmake.dir=/XXX/drishti/_ci/cmake (ninja included)

Path to error:
https://drive.google.com/file/d/1Sy77VTuBOyE52-6pK_E3voZ8wS1UJ-8m/view?usp=sharing

Thanks
Matej

**Comment by headupinclouds** [comment]
> In addition, it might be worth creating the file "local.properties",

Thanks for pointing it out.  We had discussed that one.  I think it will just need to be documented clearly, since users will typically want to specify the locations on their own.  For example, I don't use the hunter_env.sh setup script (and polly install-ci-dependencies.py proved CMake, so there isn't really a standardized path to hard code.  This application stuff all warrants some additional documentation and perhaps a few follow up tweaks.

> hunter ** FATAL ERROR **] Git directory is dirty: 

By default the drishti libs will be linked through hunter using the `GIT_SELF` feature.  See:

https://github.com/elucideye/drishti/blob/a3249da0f7fb4929d54bea5eb4647a2651ac2647/src/examples/facefilter/android-studio/app/build.gradle#L41

This triggers an on-the-fly release from the current repo, and I think having any local files that aren't in .gitignore will lead to that error.  I'm not sure if that can be relaxed or not.  Can you try again from a "clean" repo?  You can also set `GIT_SELF=OFF` in the gradle file above and it should bundle the sources directly.  That will be useful for integrated debugging anyway.

Much of this is migrated from a different project and we'll be updating the CI configs to run the Android Studio builds, so that should help provide a working example in addition to the documentation.  Eventually we'll find some time to update the tracking.

I'll open a documentation issue for now and will try to take a look soon.

Thanks
