### ISSUE TITLE
OpenCV build error with toolchain ios-nocodesign-11-4-dep-9-3

### ISSUE THREAD

**Issue by ygyin-ivy** [elucideye/drishti#721]
[log.txt](https://github.com/elucideye/drishti/files/2309388/log.txt)

xcode  9.4
ios       11.4
toolchain  ios-nocodesign-11-4-dep-9-3

**Comment by headupinclouds** [comment]
The `nocodesign` toolchain will work fine for build tests, but I you can't run the final executable on a device.

Can you post these files?
```
See also "/Users/ivy/.hunter/_Base/f58bcf2/9e7542d/48de53c/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/CMakeFiles/CMakeOutput.log".
See also "/Users/ivy/.hunter/_Base/f58bcf2/9e7542d/48de53c/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/CMakeFiles/CMakeError.log".
```

**Comment by ygyin-ivy** [comment]
[CMakeOutput.txt](https://github.com/elucideye/drishti/files/2310106/CMakeOutput.txt)
[CMakeError.txt](https://github.com/elucideye/drishti/files/2310105/CMakeError.txt)

**Comment by headupinclouds** [comment]
```
=== BUILD TARGET cmTC_71225 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Warning: "cmTC_71225" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
```

This looks like a CMAKE_TRY_COMPILE issue, as discussed [here](https://polly.readthedocs.io/en/latest/toolchains/ios/errors/polly_ios_bundle_identifier.html#polly-ios-bundle-identifier).  My guess is that this is somehow related to your enterprise account.  The CI builds use `nocodesign-*` toolchains without issue.  Since `nocodesign-*` won't be of much practical benefit, let's focus on your build in #720 .
